### PR TITLE
RV12 Datasheet v1.1 Release

### PR DESCRIPTION
**Pull request by sphardy**
I have updated the RV12 datasheet to put it into a potential release state.

- Version number updated to v1.1 (v1.0 is the RV11 datasheet we had previously)
- Titles & Headers now properly parameterised (update via singel file)
- Cleaned up content of chapters (minro formatting changes, typos corrected etc)
- Pipeline Chapter *removed*
  - I think we should add that back in a later revision rather than it hold up release
- Updated README to remove reference to Docs being In Development
- Tested Markdown format locally - shouldn't need any corrections when compiled for GH Pages

Is the RV12 Source code also final? Or at least in a release form? If so we can tag as a formal release

### CODE REVIEW

**Comment by rherveille** [comment]
RV12 code is complete and tested. Obviously continuously under development, but stable for release.
Pipeline drawing is missing the DIVIDER unit (in execute).

**Comment by sphardy** [comment]
_"Pipeline drawing is missing the DIVIDER unit (in execute)."_

Which diagram?

**Comment by rherveille** [comment]
Pipeline-Overview.png

**Comment by sphardy** [comment]
Found the README links to submodules we not complete - have pushed an update

**Pull request merged**
